from __future__ import annotations

from pathlib import Path

G = 9.81
AIR_GAS_CONSTANT = 287.05
AIR_HEAT_CAPACITY_RATIO = 1.4
SUTHERLAND_MU0 = 1.716e-5
SUTHERLAND_T0 = 273.15
SUTHERLAND_S = 111.0
MIN_PRESSURE_ATM = 0.001
MAX_REQUEST_BODY_BYTES = 16 * 1024
BASE_DIR = Path(__file__).resolve().parent.parent
ASSETS_DIR = BASE_DIR / "assets"
RESOLVED_ASSETS_DIR = ASSETS_DIR.resolve()
API_KEY_ENV_VAR = "BALLISTICS_API_KEY"
ALLOWED_ORIGINS_ENV_VAR = "BALLISTICS_ALLOWED_ORIGINS"
PUBLIC_MODE_ENV_VAR = "BALLISTICS_PUBLIC_MODE"
SESSION_SECRET_ENV_VAR = "BALLISTICS_SESSION_SECRET"
SESSION_COOKIE_NAME = "ballistics_session"
LOCAL_DEVELOPMENT_SESSION_SECRET = "local-dev-not-for-production"
BOOTSTRAP_CHALLENGE_TTL_SECONDS = 600
MIN_DT = 0.001
MAX_DT = 0.1
MIN_ANGLE_DEG = 0.0
MAX_ANGLE_DEG = 90.0
MIN_SPEED = 0.0
MAX_SPEED = 600.0
MIN_TEMPERATURE_C = -80.0
MAX_TEMPERATURE_C = 80.0
MAX_PRESSURE_ATM = 2.0
MIN_DIAMETER_M = 0.001
MAX_DIAMETER_M = 1.0
MIN_MATERIAL_DENSITY = 1.0
MAX_MATERIAL_DENSITY = 50000.0
MIN_SPHERICITY = 0.05
MAX_SPHERICITY = 1.0
MIN_VOLUME_FACTOR = 0.05
MAX_VOLUME_FACTOR = 20.0
