from __future__ import annotations

from ballistics.constants import DEFAULT_SHELL_DRAG_MODEL, MIN_PRESSURE_ATM
from ballistics.physics.drag import material_density_from_mass_and_diameter

DEFAULT_SIMULATION_PARAMS = {
    "angle": 45.0,
    "speed": 55.0,
    "materialDensity": material_density_from_mass_and_diameter(1.0, 0.113),
    "temperature": 15.0,
    "pressure": 1.0,
    "diameter": 0.113,
    "dt": 0.016,
    "projectileShape": "sphere",
    "sphericity": 1.0,
    "volumeFactor": 1.0,
    "dragModel": DEFAULT_SHELL_DRAG_MODEL,
    "ballisticCoefficient": 0.0,
}

REFERENCE_PRESETS = {
    "vacuum": {
        "angle": 45.0,
        "speed": 50.0,
        "materialDensity": material_density_from_mass_and_diameter(1.0, 0.113),
        "temperature": 15.0,
        "pressure": MIN_PRESSURE_ATM,
        "diameter": 0.113,
        "dt": 0.016,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "highDrag": {
        "angle": 42.0,
        "speed": 48.0,
        "materialDensity": material_density_from_mass_and_diameter(0.45, 0.239),
        "temperature": 30.0,
        "pressure": 1.05,
        "diameter": 0.239,
        "dt": 0.012,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "heavy": {
        "angle": 45.0,
        "speed": 55.0,
        "materialDensity": material_density_from_mass_and_diameter(8.0, 0.124),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.124,
        "dt": 0.016,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "longRange": {
        "angle": 34.0,
        "speed": 120.0,
        "materialDensity": material_density_from_mass_and_diameter(5.0, 0.101),
        "temperature": 5.0,
        "pressure": 0.9,
        "diameter": 0.101,
        "dt": 0.01,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
}

HISTORICAL_PLOT_REFERENCE_PARAMS = {
    "ballista": {
        "angle": 35.0,
        "speed": 70.0,
        "materialDensity": material_density_from_mass_and_diameter(0.85, 0.05, 4.6),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.05,
        "dt": 0.016,
        "projectileShape": "shell",
        "sphericity": 0.4,
        "volumeFactor": 4.6,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.12,
    },
    "mangonel": {
        "angle": 38.0,
        "speed": 42.0,
        "materialDensity": material_density_from_mass_and_diameter(12.0, 0.18),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.18,
        "dt": 0.02,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "trebuchet": {
        "angle": 43.0,
        "speed": 55.0,
        "materialDensity": material_density_from_mass_and_diameter(30.0, 0.28),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.28,
        "dt": 0.02,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "saker": {
        "angle": 15.0,
        "speed": 164.0,
        "materialDensity": material_density_from_mass_and_diameter(2.38, 0.083),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.083,
        "dt": 0.016,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "basilisk": {
        "angle": 16.0,
        "speed": 134.0,
        "materialDensity": material_density_from_mass_and_diameter(4.54, 0.121),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.121,
        "dt": 0.02,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "culverin": {
        "angle": 9.0,
        "speed": 408.0,
        "materialDensity": material_density_from_mass_and_diameter(9.07, 0.14),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.14,
        "dt": 0.012,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "demiCulverin": {
        "angle": 14.0,
        "speed": 145.0,
        "materialDensity": material_density_from_mass_and_diameter(3.63, 0.102),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.102,
        "dt": 0.016,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "falconet": {
        "angle": 17.0,
        "speed": 122.0,
        "materialDensity": material_density_from_mass_and_diameter(0.45, 0.051),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.051,
        "dt": 0.018,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "demiCannon": {
        "angle": 11.0,
        "speed": 95.0,
        "materialDensity": material_density_from_mass_and_diameter(14.5, 0.159),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.159,
        "dt": 0.02,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "gribeauval": {
        "angle": 18.0,
        "speed": 133.0,
        "materialDensity": material_density_from_mass_and_diameter(5.88, 0.121),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.121,
        "dt": 0.02,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "m1841SixPounder": {
        "angle": 5.0,
        "speed": 1450.0 * 0.3048,
        "materialDensity": material_density_from_mass_and_diameter(2.72155, 0.093218),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.093218,
        "dt": 0.01,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "paixhans": {
        "angle": 5.0,
        "speed": 400.0,
        "materialDensity": material_density_from_mass_and_diameter(30.0, 0.22, 1.35),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.22,
        "dt": 0.01,
        "projectileShape": "shell",
        "sphericity": 0.72,
        "volumeFactor": 1.35,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.19,
    },
    "armstrong": {
        "angle": 8.0,
        "speed": 378.0,
        "materialDensity": material_density_from_mass_and_diameter(5.1, 0.076, 2.85),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.076,
        "dt": 0.01,
        "projectileShape": "shell",
        "sphericity": 0.64,
        "volumeFactor": 2.85,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.24,
    },
    "ordnance": {
        "angle": 10.0,
        "speed": 370.0,
        "materialDensity": material_density_from_mass_and_diameter(4.3, 0.076, 2.4),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.076,
        "dt": 0.01,
        "projectileShape": "shell",
        "sphericity": 0.66,
        "volumeFactor": 2.4,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.22,
    },
    "napoleon": {
        "angle": 12.0,
        "speed": 439.0,
        "materialDensity": material_density_from_mass_and_diameter(5.44, 0.117),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.117,
        "dt": 0.012,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "parrott": {
        "angle": 5.0,
        "speed": 375.0,
        "materialDensity": material_density_from_mass_and_diameter(4.3, 0.074, 2.6),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.074,
        "dt": 0.01,
        "projectileShape": "shell",
        "sphericity": 0.65,
        "volumeFactor": 2.6,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.21,
    },
    "longGun24": {
        "angle": 6.0,
        "speed": 450.0,
        "materialDensity": material_density_from_mass_and_diameter(10.89, 0.1522),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.1522,
        "dt": 0.012,
        "projectileShape": "sphere",
        "sphericity": 1.0,
        "volumeFactor": 1.0,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.0,
    },
    "french75": {
        "angle": 12.0,
        "speed": 500.0,
        "materialDensity": material_density_from_mass_and_diameter(5.3, 0.075, 2.35),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.075,
        "dt": 0.01,
        "projectileShape": "shell",
        "sphericity": 0.72,
        "volumeFactor": 2.35,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.24,
    },
    "qf18Pounder": {
        "angle": 11.0,
        "speed": 492.0,
        "materialDensity": material_density_from_mass_and_diameter(8.4, 0.084, 2.45),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.084,
        "dt": 0.01,
        "projectileShape": "shell",
        "sphericity": 0.71,
        "volumeFactor": 2.45,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.25,
    },
    "lefh16": {
        "angle": 24.0,
        "speed": 395.0,
        "materialDensity": material_density_from_mass_and_diameter(14.81, 0.105, 2.65),
        "temperature": 15.0,
        "pressure": 1.0,
        "diameter": 0.105,
        "dt": 0.012,
        "projectileShape": "shell",
        "sphericity": 0.69,
        "volumeFactor": 2.65,
        "dragModel": DEFAULT_SHELL_DRAG_MODEL,
        "ballisticCoefficient": 0.27,
    },
}
